### ISSUE TITLE
build success but can't reslove url in webpack and can't resolve url in css

### ISSUE THREAD

**Issue by bigbigbo** [rollup/rollup-plugin-url#18]
I use rollup build my react component, but have two questions.

first, build success but webpack can't resolve such a url:
```js
var loadingIcon = './static/images/loading-24b7d7fd646f1365.gif';
React.createElement('img', { className: 'loading-img', src: loadingIcon, alt: '' })
```
I think `rollup-plugin-url` is right, but I have to add `var loadingIcon = require( './static/images/loading-24b7d7fd646f1365.gif';)` myself .

senond, rollup-plugin-url can't resolve url in css:
```css
.demo {
  background-image: url("./loading.gif");
}
```
`rollup-plugin-url` can't resolve this url.

Did I do something wrong with it ?  Or should I not use rollup to package my component library ?

**Comment by Ashot-KR** [comment]
Hi!
> first, build success but webpack can't resolve such a url:

The problem is that `rollup-plugin-url` generates static relative path to files (`var img = "40b22a240bb599f3.jpg";`), but in case of library webpack needs import of image (e.g. `var img = require('./some-img.png')`). 

Looks like plugin needs an option to generate `var img = require('./40b22a240bb599f3.jpg')` instead of  `var img = "40b22a240bb599f3.jpg";`, but i have no idea how to do it 😄. And i'm not sure it's possible, and not sure `rollup-plugin-url` should have such functionality – this questions need some research.

For now you could try following method:
1. add images to `external` option in your rollup config
2. use any plugin to copy images to your dist folder (e.g. `rollup-plugin-copy-glob`)

Another dirty solution: set `limit` options to higher value, so images will be included as base64 in `js` files.

> senond, rollup-plugin-url can't resolve url in css

`rollup-plugin-url` doesn't process `css` files. You should use use css processor (e.g. `postcss` with `postcss-url` plugin or something like that)

**Comment by bigbigbo** [comment]
Thank you for your answer.
On the first question, I fork from `rollup-plugin-url` and try build a [rollup-plugin-assert-url](https://github.com/bigbigbo/rollup-plugin-asset-url). 

On the second question, thank you for your suggestion and I'll study it. :tada:

**Comment by sormy** [comment]
There is rollup-plugin-postcss and postcss plugin to rebase url with customizable url rebase handler that could be used to implement any rebase logic.

Here is a snippet of rebase import-like plugin that works for assets imported directly from JS:

```js
function asset(opts) {
  const extensions = (opts && opts.extensions) || []
  const assetsPath = (opts && opts.assetsPath) || ""

  return {
    load(id) {
      const isAsset = extensions.reduce((result, ext) => (result || extname(id) === ext), false)
      if (isAsset) {
        const destPath = join(assetsPath, basename(id))
        const importPath = "./" + relative(distDir, destPath)
        copyFileSync(id, destPath)
        return `export default require("${importPath}")`
      }
    }
  }
}
```

PS: I create an "rollup-plugin-smart-asset" alternative to this plugin, with MIT license and and a lot of different options. It also has `keepImport` feature like explained above.

**Comment by bigbigbo** [comment]
> There is rollup-plugin-postcss and postcss plugin to rebase url with customizable url rebase handler that could be used to implement any rebase logic.
> 
> Here is a snippet of rebase import-like plugin that works for assets imported directly from JS:
> 
> ```js
> function asset(opts) {
>   const extensions = (opts && opts.extensions) || []
>   const assetsPath = (opts && opts.assetsPath) || ""
> 
>   return {
>     load(id) {
>       const isAsset = extensions.reduce((result, ext) => (result || extname(id) === ext), false)
>       if (isAsset) {
>         const destPath = join(assetsPath, basename(id))
>         const importPath = "./" + relative(distDir, destPath)
>         copyFileSync(id, destPath)
>         return `export default require("${importPath}")`
>       }
>     }
>   }
> }
> ```
> 
> PS: I create an "rollup-plugin-smart-asset" alternative to this plugin, with MIT license and and a lot of different options. It also has `keepImport` feature like explained above.

thx :smile:
