### ISSUE TITLE
Request to change the license

### ISSUE THREAD

**Issue by sormy** [rollup/rollup-plugin-url#20]
LGPL-3.0 is not permissive and is banned in large companies. Rollup itself is MIT and most of the plugins also. I guess it could be good to change license for this package to MIT too.

**Comment by Ashot-KR** [comment]
Plugin author is @Swatinem, so i think we should ask him a permission to change licence.

**Comment by Swatinem** [comment]
Oh here goes the religious war :-D

Well my take on it is that I don’t want anyone to create a proprietary fork of my work and charge people money for it without contributing back any improvements, which *"permissive"* licenses allow you to do.

In any case, rollup and all the plugins are dev tools, so you will probably never redistribute it as part of a proprietary project. Unless that project is strictly about being a devtool. In which case you better contribute improvements upstream!

Having said that… I have basically zero involvement in `rollup-plugin-url` since a few years, so @Ashot-KR if you feel changing the license is the right decision, I won’t veto it.

**Comment by sormy** [comment]
Do you really afraid that somebody could get benefits from 122 lines of code? :-)
In large corporations GPL is banned since it is hard to control if modification happens, especially if it is 122 lines of code, especially if there is alternative like webpack that has all plugins under MIT/Apache2 license. It is just harmful for rollup to have basic plugins to be not on permissive license.
I personally rewrote `rollup-plugin-url` just to get rid of GPL3: https://github.com/sormy/rollup-plugin-smart-asset

**Comment by Ashot-KR** [comment]
version 3.0.0 is on MIT License
